### PR TITLE
Added more customization and Update readme 1.4

### PR DESCRIPTION
**Pull request by MinceMan**
It maybe easiest to look at individual commits. I would love to see this get to master, so question everything. The way we format code is a little bit different so I can change any formatting. 

Also I noticed that Italian, German and Traditional Chinese translations do not appear in master. Not sure where they went...
- Removed unnecessary dependency in library. Updated to latest versions of Gradle
- Refactored building ShowDialogActions from the builder to a Factory. This let's impletmenters of the app to easily hijack the first Action.
- Added the ablity to customize the email subject and email message. Added to Sample an example on a customized email message.
- Updated readme and versions to 1.4 - I think I said I would do this like 6 months ago :-)

**Bonus** Fragment dialog looks great on Android 5.0 :smile:

### CODE REVIEW

**Comment by mariosangiorgio** [comment]
For some reason the build on Travis CI failed. Would you mind having a look at it?
https://travis-ci.org/mariosangiorgio/RateMyApp/builds/38652172

Unfortunately this evening I've been a bit busy and now I have to go to sleep. I'm going to review your code and give some feedbacks tomorrow.

I'm happy to integrate any contribution to master, especially now that I am no more actively developing the project so thank you for your pull request

**Comment by MinceMan** [comment]
SDK information in Travis just needed to be updated. It is passing now.

**Comment by mariosangiorgio** [comment]
Thanks. Tomorrow I'll have a look at the your changes and merge them

**Comment by mariosangiorgio** [comment]
All looks good to me. I just merged the pull request. Thanks again for your contribution!

**Pull request merged**
